

name: "Builda"
on:
  push:
    tags: '*'

jobs:
  build:
    name: "Build Unitrix kernel"
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout kernel source"
      uses: actions/checkout@v2
      with:
        repository:  yoptah/android_kernel_xiaomi_sdm710

    - name: "Set variables"
      id: vars
      run: |
        echo "::set-output name=short_sha::$(git rev-parse HEAD | cut -b 1-8 -)"
        echo "::set-output name=release_name::Dark-Ages-Último"
    - name: "Checkout zipper"
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3
        path: zipper
    - name: "Android kernel build"
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME:  AXTyHr pyxis kernel
      with:
        arch: arm64
        compiler: proton-clang/master/binutils
        defconfig: 3_defconfig
        image: Image.gz-dt
   
    - name: Release build
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.build.outputs.outfile }}
        token: ${{ secrets.GITHUB_TOKEN }}
        
