name: Build on Tag

on:
  push:
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3
        path: zipper
    - name: Android Kernel Action_liblz4
      uses: shuxiangfan/android-kernel-actions@v0.3.4
      id: build
      env:
        NAME: AXTyHr
      with:
        arch: arm64
        compiler: proton-clang/master, proton-clang/09fb113/binutils
        defconfig: 3_defconfig
        image: Image.gz-dtb

    - name: Release build
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.build.outputs.outfile }}
        token: ${{ secrets.GITHUB_TOKEN }}

